package com.sh.db.dao;

import com.sh.db.domain.ShAccountTrace;
import com.sh.db.domain.ShAccountTraceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShAccountTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     */
    long countByExample(ShAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     */
    int deleteByExample(ShAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     */
    int insert(ShAccountTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     */
    int insertSelective(ShAccountTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAccountTrace selectOneByExample(ShAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAccountTrace selectOneByExampleSelective(@Param("example") ShAccountTraceExample example, @Param("selective") ShAccountTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShAccountTrace> selectByExampleSelective(@Param("example") ShAccountTraceExample example, @Param("selective") ShAccountTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     */
    List<ShAccountTrace> selectByExample(ShAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAccountTrace selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShAccountTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     */
    ShAccountTrace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShAccountTrace record, @Param("example") ShAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShAccountTrace record, @Param("example") ShAccountTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShAccountTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_account_trace
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShAccountTrace record);
}