package com.sh.db.dao;

import com.sh.db.domain.ShAdmin;
import com.sh.db.domain.ShAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     */
    long countByExample(ShAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     */
    int deleteByExample(ShAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     */
    int insert(ShAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     */
    int insertSelective(ShAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAdmin selectOneByExample(ShAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAdmin selectOneByExampleSelective(@Param("example") ShAdminExample example, @Param("selective") ShAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShAdmin> selectByExampleSelective(@Param("example") ShAdminExample example, @Param("selective") ShAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     */
    List<ShAdmin> selectByExample(ShAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     */
    ShAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShAdmin record, @Param("example") ShAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShAdmin record, @Param("example") ShAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}