package com.sh.db.dao;

import com.sh.db.domain.ShAddress;
import com.sh.db.domain.ShAddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     */
    long countByExample(ShAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     */
    int deleteByExample(ShAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     */
    int insert(ShAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     */
    int insertSelective(ShAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAddress selectOneByExample(ShAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAddress selectOneByExampleSelective(@Param("example") ShAddressExample example, @Param("selective") ShAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShAddress> selectByExampleSelective(@Param("example") ShAddressExample example, @Param("selective") ShAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     */
    List<ShAddress> selectByExample(ShAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAddress selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShAddress.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     */
    ShAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAddress selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShAddress record, @Param("example") ShAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShAddress record, @Param("example") ShAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_address
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}