package com.sh.db.dao;

import com.sh.db.domain.ShAd;
import com.sh.db.domain.ShAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     */
    long countByExample(ShAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     */
    int deleteByExample(ShAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     */
    int insert(ShAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     */
    int insertSelective(ShAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAd selectOneByExample(ShAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAd selectOneByExampleSelective(@Param("example") ShAdExample example, @Param("selective") ShAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShAd> selectByExampleSelective(@Param("example") ShAdExample example, @Param("selective") ShAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     */
    List<ShAd> selectByExample(ShAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAd selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShAd.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     */
    ShAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAd selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShAd record, @Param("example") ShAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShAd record, @Param("example") ShAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_ad
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}