package com.sh.db.dao;

import com.sh.db.domain.ShAftersale;
import com.sh.db.domain.ShAftersaleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShAftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     */
    long countByExample(ShAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(ShAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     */
    int insert(ShAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     */
    int insertSelective(ShAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAftersale selectOneByExample(ShAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAftersale selectOneByExampleSelective(@Param("example") ShAftersaleExample example, @Param("selective") ShAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShAftersale> selectByExampleSelective(@Param("example") ShAftersaleExample example, @Param("selective") ShAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     */
    List<ShAftersale> selectByExample(ShAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     */
    ShAftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShAftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShAftersale record, @Param("example") ShAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShAftersale record, @Param("example") ShAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_aftersale
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}