package com.sh.db.dao;

import com.sh.db.domain.ShArticle;
import com.sh.db.domain.ShArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    long countByExample(ShArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    int deleteByExample(ShArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    int insert(ShArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    int insertSelective(ShArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShArticle selectOneByExample(ShArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShArticle selectOneByExampleSelective(@Param("example") ShArticleExample example, @Param("selective") ShArticle.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShArticle selectOneByExampleWithBLOBs(ShArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShArticle> selectByExampleSelective(@Param("example") ShArticleExample example, @Param("selective") ShArticle.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    List<ShArticle> selectByExampleWithBLOBs(ShArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    List<ShArticle> selectByExample(ShArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShArticle selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShArticle.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    ShArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShArticle selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShArticle record, @Param("example") ShArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ShArticle record, @Param("example") ShArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShArticle record, @Param("example") ShArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ShArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}