package com.sh.db.dao;

import com.sh.db.domain.ShBrand;
import com.sh.db.domain.ShBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     */
    long countByExample(ShBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     */
    int deleteByExample(ShBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     */
    int insert(ShBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     */
    int insertSelective(ShBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShBrand selectOneByExample(ShBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShBrand selectOneByExampleSelective(@Param("example") ShBrandExample example, @Param("selective") ShBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShBrand> selectByExampleSelective(@Param("example") ShBrandExample example, @Param("selective") ShBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     */
    List<ShBrand> selectByExample(ShBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShBrand selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShBrand.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     */
    ShBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShBrand selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShBrand record, @Param("example") ShBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShBrand record, @Param("example") ShBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_brand
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}