package com.sh.db.dao;

import com.sh.db.domain.ShCart;
import com.sh.db.domain.ShCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     */
    long countByExample(ShCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     */
    int deleteByExample(ShCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     */
    int insert(ShCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     */
    int insertSelective(ShCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCart selectOneByExample(ShCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCart selectOneByExampleSelective(@Param("example") ShCartExample example, @Param("selective") ShCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShCart> selectByExampleSelective(@Param("example") ShCartExample example, @Param("selective") ShCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     */
    List<ShCart> selectByExample(ShCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCart selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShCart.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     */
    ShCart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCart selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShCart record, @Param("example") ShCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShCart record, @Param("example") ShCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_cart
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}