package com.sh.db.dao;

import com.sh.db.domain.ShCategory;
import com.sh.db.domain.ShCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     */
    long countByExample(ShCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     */
    int deleteByExample(ShCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     */
    int insert(ShCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     */
    int insertSelective(ShCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCategory selectOneByExample(ShCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCategory selectOneByExampleSelective(@Param("example") ShCategoryExample example, @Param("selective") ShCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShCategory> selectByExampleSelective(@Param("example") ShCategoryExample example, @Param("selective") ShCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     */
    List<ShCategory> selectByExample(ShCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCategory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShCategory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     */
    ShCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCategory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShCategory record, @Param("example") ShCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShCategory record, @Param("example") ShCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_category
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}