package com.sh.db.dao;

import com.sh.db.domain.ShCouponUser;
import com.sh.db.domain.ShCouponUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShCouponUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     */
    long countByExample(ShCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     */
    int deleteByExample(ShCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     */
    int insert(ShCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     */
    int insertSelective(ShCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCouponUser selectOneByExample(ShCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCouponUser selectOneByExampleSelective(@Param("example") ShCouponUserExample example, @Param("selective") ShCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShCouponUser> selectByExampleSelective(@Param("example") ShCouponUserExample example, @Param("selective") ShCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     */
    List<ShCouponUser> selectByExample(ShCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCouponUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShCouponUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     */
    ShCouponUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShCouponUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShCouponUser record, @Param("example") ShCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShCouponUser record, @Param("example") ShCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShCouponUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShCouponUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_coupon_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}