package com.sh.db.dao;

import com.sh.db.domain.ShDelPicture;
import com.sh.db.domain.ShDelPictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShDelPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     */
    long countByExample(ShDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     */
    int deleteByExample(ShDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     */
    int insert(ShDelPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     */
    int insertSelective(ShDelPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShDelPicture selectOneByExample(ShDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShDelPicture selectOneByExampleSelective(@Param("example") ShDelPictureExample example, @Param("selective") ShDelPicture.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShDelPicture> selectByExampleSelective(@Param("example") ShDelPictureExample example, @Param("selective") ShDelPicture.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     */
    List<ShDelPicture> selectByExample(ShDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShDelPicture selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShDelPicture.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     */
    ShDelPicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShDelPicture record, @Param("example") ShDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShDelPicture record, @Param("example") ShDelPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShDelPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_del_picture
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShDelPicture record);
}