package com.sh.db.dao;

import com.sh.db.domain.ShFeedback;
import com.sh.db.domain.ShFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     */
    long countByExample(ShFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     */
    int deleteByExample(ShFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     */
    int insert(ShFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     */
    int insertSelective(ShFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShFeedback selectOneByExample(ShFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShFeedback selectOneByExampleSelective(@Param("example") ShFeedbackExample example, @Param("selective") ShFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShFeedback> selectByExampleSelective(@Param("example") ShFeedbackExample example, @Param("selective") ShFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     */
    List<ShFeedback> selectByExample(ShFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShFeedback selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShFeedback.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     */
    ShFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShFeedback selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShFeedback record, @Param("example") ShFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShFeedback record, @Param("example") ShFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_feedback
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}