package com.sh.db.dao;

import com.sh.db.domain.ShFootprint;
import com.sh.db.domain.ShFootprintExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     */
    long countByExample(ShFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     */
    int deleteByExample(ShFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     */
    int insert(ShFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     */
    int insertSelective(ShFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShFootprint selectOneByExample(ShFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShFootprint selectOneByExampleSelective(@Param("example") ShFootprintExample example, @Param("selective") ShFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShFootprint> selectByExampleSelective(@Param("example") ShFootprintExample example, @Param("selective") ShFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     */
    List<ShFootprint> selectByExample(ShFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShFootprint selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShFootprint.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     */
    ShFootprint selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShFootprint selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShFootprint record, @Param("example") ShFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShFootprint record, @Param("example") ShFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShFootprintExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_footprint
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}