package com.sh.db.dao;

import com.sh.db.domain.ShGoodsSpecification;
import com.sh.db.domain.ShGoodsSpecificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShGoodsSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     */
    long countByExample(ShGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     */
    int deleteByExample(ShGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     */
    int insert(ShGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     */
    int insertSelective(ShGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsSpecification selectOneByExample(ShGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsSpecification selectOneByExampleSelective(@Param("example") ShGoodsSpecificationExample example, @Param("selective") ShGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShGoodsSpecification> selectByExampleSelective(@Param("example") ShGoodsSpecificationExample example, @Param("selective") ShGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     */
    List<ShGoodsSpecification> selectByExample(ShGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsSpecification selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShGoodsSpecification.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     */
    ShGoodsSpecification selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsSpecification selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShGoodsSpecification record, @Param("example") ShGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShGoodsSpecification record, @Param("example") ShGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShGoodsSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShGoodsSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_specification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}