package com.sh.db.dao;

import com.sh.db.domain.ShGoodsProduct;
import com.sh.db.domain.ShGoodsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShGoodsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     */
    long countByExample(ShGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     */
    int deleteByExample(ShGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     */
    int insert(ShGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     */
    int insertSelective(ShGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsProduct selectOneByExample(ShGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsProduct selectOneByExampleSelective(@Param("example") ShGoodsProductExample example, @Param("selective") ShGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShGoodsProduct> selectByExampleSelective(@Param("example") ShGoodsProductExample example, @Param("selective") ShGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     */
    List<ShGoodsProduct> selectByExample(ShGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsProduct selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShGoodsProduct.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     */
    ShGoodsProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsProduct selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShGoodsProduct record, @Param("example") ShGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShGoodsProduct record, @Param("example") ShGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShGoodsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShGoodsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}