package com.sh.db.dao;

import com.sh.db.domain.ShGoodsAttribute;
import com.sh.db.domain.ShGoodsAttributeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShGoodsAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     */
    long countByExample(ShGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByExample(ShGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     */
    int insert(ShGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     */
    int insertSelective(ShGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsAttribute selectOneByExample(ShGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsAttribute selectOneByExampleSelective(@Param("example") ShGoodsAttributeExample example, @Param("selective") ShGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShGoodsAttribute> selectByExampleSelective(@Param("example") ShGoodsAttributeExample example, @Param("selective") ShGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     */
    List<ShGoodsAttribute> selectByExample(ShGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsAttribute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShGoodsAttribute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     */
    ShGoodsAttribute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGoodsAttribute selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShGoodsAttribute record, @Param("example") ShGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShGoodsAttribute record, @Param("example") ShGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShGoodsAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShGoodsAttributeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_goods_attribute
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}