package com.sh.db.dao;

import com.sh.db.domain.ShGrouponRules;
import com.sh.db.domain.ShGrouponRulesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShGrouponRulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     */
    long countByExample(ShGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByExample(ShGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     */
    int insert(ShGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     */
    int insertSelective(ShGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGrouponRules selectOneByExample(ShGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGrouponRules selectOneByExampleSelective(@Param("example") ShGrouponRulesExample example, @Param("selective") ShGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShGrouponRules> selectByExampleSelective(@Param("example") ShGrouponRulesExample example, @Param("selective") ShGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     */
    List<ShGrouponRules> selectByExample(ShGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGrouponRules selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShGrouponRules.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     */
    ShGrouponRules selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShGrouponRules selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShGrouponRules record, @Param("example") ShGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShGrouponRules record, @Param("example") ShGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShGrouponRules record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShGrouponRulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_groupon_rules
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}