package com.sh.db.dao;

import com.sh.db.domain.ShIssue;
import com.sh.db.domain.ShIssueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     */
    long countByExample(ShIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     */
    int deleteByExample(ShIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     */
    int insert(ShIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     */
    int insertSelective(ShIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShIssue selectOneByExample(ShIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShIssue selectOneByExampleSelective(@Param("example") ShIssueExample example, @Param("selective") ShIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShIssue> selectByExampleSelective(@Param("example") ShIssueExample example, @Param("selective") ShIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     */
    List<ShIssue> selectByExample(ShIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     */
    ShIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShIssue record, @Param("example") ShIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShIssue record, @Param("example") ShIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_issue
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}