package com.sh.db.dao;

import com.sh.db.domain.ShKeyword;
import com.sh.db.domain.ShKeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShKeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     */
    long countByExample(ShKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     */
    int deleteByExample(ShKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     */
    int insert(ShKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     */
    int insertSelective(ShKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShKeyword selectOneByExample(ShKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShKeyword selectOneByExampleSelective(@Param("example") ShKeywordExample example, @Param("selective") ShKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShKeyword> selectByExampleSelective(@Param("example") ShKeywordExample example, @Param("selective") ShKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     */
    List<ShKeyword> selectByExample(ShKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShKeyword selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShKeyword.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     */
    ShKeyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShKeyword selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShKeyword record, @Param("example") ShKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShKeyword record, @Param("example") ShKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShKeyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShKeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_keyword
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}