package com.sh.db.dao;

import com.sh.db.domain.ShNoticeAdmin;
import com.sh.db.domain.ShNoticeAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShNoticeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     */
    long countByExample(ShNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     */
    int deleteByExample(ShNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     */
    int insert(ShNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     */
    int insertSelective(ShNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShNoticeAdmin selectOneByExample(ShNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShNoticeAdmin selectOneByExampleSelective(@Param("example") ShNoticeAdminExample example, @Param("selective") ShNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShNoticeAdmin> selectByExampleSelective(@Param("example") ShNoticeAdminExample example, @Param("selective") ShNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     */
    List<ShNoticeAdmin> selectByExample(ShNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShNoticeAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShNoticeAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     */
    ShNoticeAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShNoticeAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShNoticeAdmin record, @Param("example") ShNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShNoticeAdmin record, @Param("example") ShNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShNoticeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShNoticeAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice_admin
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}