package com.sh.db.dao;

import com.sh.db.domain.ShNotice;
import com.sh.db.domain.ShNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     */
    long countByExample(ShNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     */
    int deleteByExample(ShNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     */
    int insert(ShNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     */
    int insertSelective(ShNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShNotice selectOneByExample(ShNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShNotice selectOneByExampleSelective(@Param("example") ShNoticeExample example, @Param("selective") ShNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShNotice> selectByExampleSelective(@Param("example") ShNoticeExample example, @Param("selective") ShNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     */
    List<ShNotice> selectByExample(ShNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     */
    ShNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShNotice record, @Param("example") ShNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShNotice record, @Param("example") ShNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_notice
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}