package com.sh.db.dao;

import com.sh.db.domain.ShOrder;
import com.sh.db.domain.ShOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     */
    long countByExample(ShOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     */
    int deleteByExample(ShOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     */
    int insert(ShOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     */
    int insertSelective(ShOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShOrder selectOneByExample(ShOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShOrder selectOneByExampleSelective(@Param("example") ShOrderExample example, @Param("selective") ShOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShOrder> selectByExampleSelective(@Param("example") ShOrderExample example, @Param("selective") ShOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     */
    List<ShOrder> selectByExample(ShOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     */
    ShOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShOrder record, @Param("example") ShOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShOrder record, @Param("example") ShOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}