package com.sh.db.dao;

import com.sh.db.domain.ShPermission;
import com.sh.db.domain.ShPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     */
    long countByExample(ShPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     */
    int deleteByExample(ShPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     */
    int insert(ShPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     */
    int insertSelective(ShPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShPermission selectOneByExample(ShPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShPermission selectOneByExampleSelective(@Param("example") ShPermissionExample example, @Param("selective") ShPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShPermission> selectByExampleSelective(@Param("example") ShPermissionExample example, @Param("selective") ShPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     */
    List<ShPermission> selectByExample(ShPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     */
    ShPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShPermission record, @Param("example") ShPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShPermission record, @Param("example") ShPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_permission
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}