package com.sh.db.dao;

import com.sh.db.domain.ShRefundTrace;
import com.sh.db.domain.ShRefundTraceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShRefundTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     */
    long countByExample(ShRefundTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     */
    int deleteByExample(ShRefundTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     */
    int insert(ShRefundTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     */
    int insertSelective(ShRefundTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShRefundTrace selectOneByExample(ShRefundTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShRefundTrace selectOneByExampleSelective(@Param("example") ShRefundTraceExample example, @Param("selective") ShRefundTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShRefundTrace> selectByExampleSelective(@Param("example") ShRefundTraceExample example, @Param("selective") ShRefundTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     */
    List<ShRefundTrace> selectByExample(ShRefundTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShRefundTrace selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShRefundTrace.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     */
    ShRefundTrace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShRefundTrace selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShRefundTrace record, @Param("example") ShRefundTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShRefundTrace record, @Param("example") ShRefundTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShRefundTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShRefundTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShRefundTraceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_refund_trace
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}