package com.sh.db.dao;

import com.sh.db.domain.ShRole;
import com.sh.db.domain.ShRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     */
    long countByExample(ShRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     */
    int deleteByExample(ShRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     */
    int insert(ShRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     */
    int insertSelective(ShRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShRole selectOneByExample(ShRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShRole selectOneByExampleSelective(@Param("example") ShRoleExample example, @Param("selective") ShRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShRole> selectByExampleSelective(@Param("example") ShRoleExample example, @Param("selective") ShRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     */
    List<ShRole> selectByExample(ShRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     */
    ShRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShRole record, @Param("example") ShRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShRole record, @Param("example") ShRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_role
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}