package com.sh.db.dao;

import com.sh.db.domain.ShSearchHistory;
import com.sh.db.domain.ShSearchHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShSearchHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     */
    long countByExample(ShSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     */
    int deleteByExample(ShSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     */
    int insert(ShSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     */
    int insertSelective(ShSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShSearchHistory selectOneByExample(ShSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShSearchHistory selectOneByExampleSelective(@Param("example") ShSearchHistoryExample example, @Param("selective") ShSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShSearchHistory> selectByExampleSelective(@Param("example") ShSearchHistoryExample example, @Param("selective") ShSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     */
    List<ShSearchHistory> selectByExample(ShSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShSearchHistory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShSearchHistory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     */
    ShSearchHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShSearchHistory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShSearchHistory record, @Param("example") ShSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShSearchHistory record, @Param("example") ShSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShSearchHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShSearchHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_search_history
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}