package com.sh.db.dao;

import com.sh.db.domain.ShStorage;
import com.sh.db.domain.ShStorageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShStorageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     */
    long countByExample(ShStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     */
    int deleteByExample(ShStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     */
    int insert(ShStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     */
    int insertSelective(ShStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShStorage selectOneByExample(ShStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShStorage selectOneByExampleSelective(@Param("example") ShStorageExample example, @Param("selective") ShStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShStorage> selectByExampleSelective(@Param("example") ShStorageExample example, @Param("selective") ShStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     */
    List<ShStorage> selectByExample(ShStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShStorage selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShStorage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     */
    ShStorage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShStorage selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShStorage record, @Param("example") ShStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShStorage record, @Param("example") ShStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShStorage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShStorageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_storage
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}