package com.sh.db.dao;

import com.sh.db.domain.ShTopic;
import com.sh.db.domain.ShTopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    long countByExample(ShTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    int deleteByExample(ShTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    int insert(ShTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    int insertSelective(ShTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShTopic selectOneByExample(ShTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShTopic selectOneByExampleSelective(@Param("example") ShTopicExample example, @Param("selective") ShTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShTopic selectOneByExampleWithBLOBs(ShTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShTopic> selectByExampleSelective(@Param("example") ShTopicExample example, @Param("selective") ShTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    List<ShTopic> selectByExampleWithBLOBs(ShTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    List<ShTopic> selectByExample(ShTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShTopic selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShTopic.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    ShTopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShTopic selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShTopic record, @Param("example") ShTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ShTopic record, @Param("example") ShTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShTopic record, @Param("example") ShTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ShTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShTopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_topic
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}