package com.sh.db.dao;

import com.sh.db.domain.ShUserAccount;
import com.sh.db.domain.ShUserAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShUserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     */
    long countByExample(ShUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     */
    int deleteByExample(ShUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     */
    int insert(ShUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     */
    int insertSelective(ShUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShUserAccount selectOneByExample(ShUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShUserAccount selectOneByExampleSelective(@Param("example") ShUserAccountExample example, @Param("selective") ShUserAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShUserAccount> selectByExampleSelective(@Param("example") ShUserAccountExample example, @Param("selective") ShUserAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     */
    List<ShUserAccount> selectByExample(ShUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShUserAccount selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShUserAccount.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     */
    ShUserAccount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShUserAccount record, @Param("example") ShUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShUserAccount record, @Param("example") ShUserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShUserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShUserAccount record);
}