package com.sh.db.dao;

import com.sh.db.domain.ShUserFormid;
import com.sh.db.domain.ShUserFormidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShUserFormidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     */
    long countByExample(ShUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     */
    int deleteByExample(ShUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     */
    int insert(ShUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     */
    int insertSelective(ShUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShUserFormid selectOneByExample(ShUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShUserFormid selectOneByExampleSelective(@Param("example") ShUserFormidExample example, @Param("selective") ShUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShUserFormid> selectByExampleSelective(@Param("example") ShUserFormidExample example, @Param("selective") ShUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     */
    List<ShUserFormid> selectByExample(ShUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShUserFormid selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShUserFormid.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     */
    ShUserFormid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShUserFormid selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShUserFormid record, @Param("example") ShUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShUserFormid record, @Param("example") ShUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShUserFormid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShUserFormidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user_formid
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}