package com.sh.db.dao;

import com.sh.db.domain.ShUser;
import com.sh.db.domain.ShUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     */
    long countByExample(ShUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     */
    int deleteByExample(ShUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     */
    int insert(ShUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     */
    int insertSelective(ShUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShUser selectOneByExample(ShUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShUser selectOneByExampleSelective(@Param("example") ShUserExample example, @Param("selective") ShUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<ShUser> selectByExampleSelective(@Param("example") ShUserExample example, @Param("selective") ShUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     */
    List<ShUser> selectByExample(ShUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShUser selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") ShUser.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     */
    ShUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    ShUser selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShUser record, @Param("example") ShUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShUser record, @Param("example") ShUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByExample(@Param("example") ShUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sh_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int logicalDeleteByPrimaryKey(Integer id);
}